# -*- coding: utf-8 -*-
"""Primeiro Tópico

Automatically generated by Colab.

Original file is located at

"""

#PRIMEIRO TÓPICO

import math

def distancia(x1, y1, x2, y2):
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

try:
    print("Pontos (X Y):")
    x1, y1 = map(float, input("A: ").split())
    x2, y2 = map(float, input("B: ").split())
    x3, y3 = map(float, input("C: ").split())

    ab = distancia(x1, y1, x2, y2)
    bc = distancia(x2, y2, x3, y3)
    ca = distancia(x3, y3, x1, y1)

    print(f"Distâncias: AB={ab:.3f}, BC={bc:.3f}, CA={ca:.3f}")

    if ab + bc <= ca or ab + ca <= bc or bc + ca <= ab:
        print("Não é triângulo.")
    else:
        tol = 0.001
        if abs(ab - bc) < tol and abs(ab - ca) < tol:
            print("Equilátero")
        elif abs(ab - bc) < tol or abs(ab - ca) < tol or abs(bc - ca) < tol:
            print("Isósceles")
        else:
            print("Escaleno")
except:
    print("Erro!")
