# -*- coding: utf-8 -*-
"""Terceiro Tópico

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMqrSm59Lj8Sck7PnIFh_Pou8tRm_JU2
"""

#TERCEIRO TÓPICO

import math

def distancia(x1, y1, x2, y2):
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

tipo = input("Digite o Tipo (equilatero/isosceles/escaleno): ").lower()
sugestoes = {
    "equilatero": [(0,0), (2,0), (1, math.sqrt(3))],
    "isosceles": [(0,0), (4,0), (2,3)],
    "escaleno": [(0,0), (5,0), (1,4)]
}
if tipo in sugestoes:
    a, b, c = sugestoes[tipo]
    ab = distancia(a[0],a[1],b[0],b[1])
    bc = distancia(b[0],b[1],c[0],c[1])
    ca = distancia(c[0],c[1],a[0],a[1])
    print(f"Pontos: A({a[0]},{a[1]:.3f}) B({b[0]},{b[1]:.3f}) C({c[0]},{c[1]:.3f})")
    print(f"Distâncias: {ab:.3f}, {bc:.3f}, {ca:.3f}")
else:
    print("Inválido!")